apiVersion: apiextensions.k8s.io/v1beta1 
kind: CustomResourceDefinition 
metadata: 
  name: grafana.opcito.org 
spec: 
  scope: Namespaced 
  group: opcito.org 
  versions: 
    - name: v1 
      served: true 
      storage: true 
  names: 
    kind: Grafana 
    plural: grafana 
    singular: grafana 
    shortNames: 
      - gf 
      - gfn 
